[[manager.prepend_keymap]]
on = "!"
run = 'shell "nu.exe" --block'
desc = "Open Nu Shell here"

[[manager.prepend_keymap]]
on = "T"
run = "plugin max-preview"
desc = "Maximize or restore preview"

[[manager.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = "F"
run = "plugin smart-filter"
desc = "Smart filter"

[[manager.prepend_keymap]]
on = "<C-y>"                      # Esta es la combinación de teclas que activará el plugin.
run = ["plugin system-clipboard"]
